#include "clean_robot_pkg/strategies/zigzag_strategy.hpp"

namespace clean_robot_pkg
{

ZigZagStrategy::ZigZagStrategy(const rclcpp::Logger & logger)
: area_initialized_(false)
{
  path_manager_ = std::make_unique<CoveragePathManager>(logger);
}

void ZigZagStrategy::set_area(const geometry_msgs::msg::PolygonStamped & /*polygon*/)
{
  // Path is actually generated by external node (opennav_coverage), 
  // so we wait for set_full_path to be called.
  area_initialized_ = true;
}

void ZigZagStrategy::set_full_path(const nav_msgs::msg::Path & path)
{
  path_manager_->set_path(path);
}

nav_msgs::msg::Path ZigZagStrategy::select_next_path(double rx, double ry)
{
  auto [lane_idx, wp_idx] = path_manager_->select_next_best_lane(rx, ry);
  if (lane_idx != -1) {
    return path_manager_->get_path_from_waypoint(lane_idx, wp_idx);
  }
  return nav_msgs::msg::Path();
}

void ZigZagStrategy::update_progress(double rx, double ry)
{
  path_manager_->update_progress(rx, ry);
}

bool ZigZagStrategy::is_finished() const
{
  // Check if all lanes are CLEANED
  // size_t cleaned_count = 0;
  for (size_t i = 0; i < path_manager_->get_num_lanes(); ++i) {
    // Current PathManager doesn't expose internal statuses easily, 
    // let's assume if we can't select more lanes, it's finished or blocked.
    // For now, return false and let the Manager handle selection.
  }
  return false; 
}

} // namespace clean_robot_pkg
